# Generated by Django 5.0.6 on 2024-06-23 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0005_roombooking_cus_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roombooking',
            name='cus_phone',
        ),
    ]
